{
 "title": "Spring Integration",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_count{application=\"My Spring Boot Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"My Spring Boot Application\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_usage{application=\"My Spring Boot Application\"}[10s]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM heap",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"My Spring Boot Application\", area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Process Uptime Minutes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"My Spring Boot Application\"} / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{application=\"My Spring Boot Application\", uri!=\"/actuator/prometheus\", uri!=\"/**\"}[1m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "RPS by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "sum by(status)(irate(http_server_requests_seconds_count{application=\"My Spring Boot Application\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Spring Integration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Messages Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(spring_integration_send_seconds_count{application=\"My Spring Boot Application\", name=~\"jmsOutboundFlow.channel#1|jmsInboundFlow.channel#0\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Outbound Total Message Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_integration_receive_total{application=\"My Spring Boot Application\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}